general:
  description: Config for producing batches in production
  name: app_pvnet

input_data:
  default_history_minutes: 120
  default_forecast_minutes: 480

  gsp:
    gsp_zarr_path: !ENV ${DB_URL}
    history_minutes: 120
    forecast_minutes: 480
    time_resolution_minutes: 30
    start_datetime: "1900-01-01T00:00:00"
    end_datetime: "2100-01-01T00:00:00"
    metadata_only: false

  nwp:
    nwp_zarr_path: !ENV ${NWP_ZARR_PATH}
    history_minutes: 120
    forecast_minutes: 480
    time_resolution_minutes: 60
    nwp_channels:
      - t # live = t2m
      - dswrf
    nwp_image_size_pixels_height: 24
    nwp_image_size_pixels_width: 24

  satellite:
    satellite_zarr_path: latest.zarr.zip
    history_minutes: 90
    forecast_minutes: 0
    live_delay_minutes: 60
    time_resolution_minutes: 5
    satellite_channels:
      - IR_016
      - IR_039
      - IR_087
      - IR_097
      - IR_108
      - IR_120
      - IR_134
      - VIS006
      - VIS008
      - WV_062
      - WV_073
    satellite_image_size_pixels_height: 24
    satellite_image_size_pixels_width: 24

  hrvsatellite:
    hrvsatellite_zarr_path: ""
    history_minutes: 60
    forecast_minutes: 0
    time_resolution_minutes: 5
    hrvsatellite_channels:
      - HRV
    hrvsatellite_image_size_pixels_height: 24
    hrvsatellite_image_size_pixels_width: 24

output_data:
  filepath: "not-needed"
